name: fraud_mobile
description: "Fraud Detection"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8        # Icons for iOS-style components
  provider: ^6.0.4               # State management
  # android_intent_plus: ^2.0.6    # Updated package for Android intents
  http: ^1.2.2
  fl_chart: ^0.55.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0          # Linting for clean code

flutter:
  uses-material-design: true

  assets:
    - assets/                    # Includes all assets in the assets folder
