# Generated by Django 4.2.16 on 2024-09-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0002_transaction_transaction_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
